Update check_listeners.yml

diff --git a/.github/workflows/check_listeners.yml b/.github/workflows/check_listeners.yml
--- a/.github/workflows/check_listeners.yml
+++ b/.github/workflows/check_listeners.yml
@@ -24,3 +24,10 @@ jobs:
         python check_listeners.py
       env:
         JMX_DIR: '.'
+    
+    # Abort upload if listeners enabled
+    - name: Fail if listeners are enabled
+      if: steps.check_listeners.outcome == 'failure'
+      run: |
+        echo "Some listeners are enabled. Upload aborted."
+        exit 1
